### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by VicoIlFico** [FrostbyteGames1/Frostbytes-Skip-Server-Movement-Check#1]
Is it possible to completely remove all the movement checks on both the server and client side for all entities and vehicles? Would that reduce memory and cpu usage and possibly improve performance when there are a lot of entities?

**Comment by FrostbyteGames1** [comment]
Thanks for the question! As far as I am aware:

> Is it possible to completely remove all the movement checks on both the server and client side

The movement check only ever happens on the server, so there isn't anything to disable on the client side.

> for all entities and vehicles

This check is only applied to players and vehicles that are currently being controlled by players, and no other entities are affected by it. This is why many player launcher designs rely on the player riding a pig that is in a boat.

> Would that reduce memory and cpu usage and possibly improve performance when there are a lot of entities?

It is possible, though the actual performance impact would be near zero, as the check already only activates for players, and even then only in very specific situations.

**Comment by VicoIlFico** [comment]
okay thank you very much for clarifying
