### ISSUE TITLE
[question] Regarding 1.21.1 onward

### ISSUE THREAD

**Issue by ajaxnotmeta** [FrostbyteGames1/Frostbytes-Skip-Server-Movement-Check#2]
as the title says, first ofall does 1.21 of this mod works on 1.21.1?(desperatly needed it since geyser player always get flaged by server) and do you plan to updates it all the way to 1.21.2 onwards?(since i recall ever since 1.19.3 mojang decided to change internal code every so often resulting Fabric/(neo)Forge need to adapt to new code almost every updates) considering that the last mod wich also disable the movement check haven't yet to be updated since 1.20.1 and another one never been updated past 1.18.2

**Comment by FrostbyteGames1** [comment]
> does 1.21 of this mod works on 1.21.1?

The 1.21 version should work with 1.21.2, since 1.21.2 didn't change any of the movement code. I haven't tested it myself though, so if you find that it doesn't work, I can update it.

> do you plan to updates it all the way to 1.21.2 onwards?

Yes, I plan on updating this mod for as long as I can.

**Comment by ajaxnotmeta** [comment]
> > does 1.21 of this mod works on 1.21.1?
> 
> The 1.21 version should work with 1.21.2, since 1.21.2 didn't change any of the movement code. I haven't tested it myself though, so if you find that it doesn't work, I can update it.
> 
> > do you plan to updates it all the way to 1.21.2 onwards?
> 
> Yes, I plan on updating this mod for as long as I can.

ah right i forgot when i opened the issues but seems like the mod just crashed immidiately
here is the attached logs https://mclo.gs/CW1Llc1

**Comment by FrostbyteGames1** [comment]
The mod is not meant to run on the client side, only on the server.

**Comment by Fantomrat** [comment]
> The mod is not meant to run on the client side, only on the server.

mod not working now
you need to update dependencies to support 1.21.1

**Comment by FrostbyteGames1** [comment]
v.1.0.1 has now been published with support for 1.21.1.
